# Generated by Django 3.0.8 on 2020-07-30 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backprojectapi', '0002_chatinmeeting'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='duration',
        ),
    ]
