# Generated by Django 3.0.8 on 2020-07-30 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backprojectapi', '0003_remove_meeting_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='startTime',
            field=models.TextField(max_length=50),
        ),
    ]
