# Generated by Django 3.0.8 on 2020-07-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backprojectapi', '0004_auto_20200730_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='typeEx',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='typeTest',
            field=models.BooleanField(),
        ),
    ]
