# Generated by Django 3.0.8 on 2020-07-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backprojectapi', '0005_auto_20200730_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='typeEx',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='typeTest',
            field=models.TextField(max_length=50),
        ),
    ]
