# Generated by Django 3.0.8 on 2020-07-31 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backprojectapi', '0007_auto_20200731_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='quizNumber',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='backprojectapi.Quiz'),
        ),
    ]
