# Generated by Django 3.0.8 on 2020-07-31 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backprojectapi', '0008_question_quiznumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quizNumber',
        ),
    ]
